sudo: false

notifications:
  email:
    on_success: never
    on_failure: always

language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - /^jedipus-.*$/

env:
   - GRADLE_VERSION="2.13"

before_install:
   - wget http://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
   - unzip gradle-$GRADLE_VERSION-bin.zip
   - export GRADLE_HOME=$PWD/gradle-$GRADLE_VERSION
   - export PATH=$GRADLE_HOME/bin:$PATH

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: /bin/true

script: if [ "$TRAVIS_PULL_REQUEST" == "true" ] && [ "$TRAVIS_BRANCH" == "master" ]; then gradle check; elif [[ "$TRAVIS_BRANCH" == jedipus* ]]; then gradle check; fi

after_success: if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ ! -z "$TRAVIS_TAG" ] ; then gradle bintrayUpload; fi
